// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlgbvornbidwvkcqnplw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsZ2J2b3JuYmlkd3ZrY3FucGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODYxMDcsImV4cCI6MjA3MTY2MjEwN30.pXANIpt-08Kk_Lk_rGJurirwO7boA_DFvLtbwDeEwTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});